[variables]
NODE_ENV = "production"
PORT = "4173"

[phases.setup]
nixPkgs = [
  'nodejs',
  'nodePackages.npm',
  'python3',
  'gcc',  # Required for native module compilation
  'gnumake',
  'pkg-config'
]
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
nixpkgsArchive = '5c37ad87222cfc1ec36d6cd1364514a9efc2f7f2'  # Verified working commit

[phases.install]
cmds = [
  "npm ci --prefer-offline --no-audit",
  "cd TrueNorthAdmin && npm ci --prefer-offline --no-audit",
  "cd server && npm ci --prefer-offline --no-audit"
]

[phases.build]
cmds = [
  "npm run build:main",
  "npm run build:admin",
  "npm run build:combine"
]

[start]
cmd = "node server.js"