[variables]
NODE_ENV = "production"
PORT = "4173"

[phases.setup]
nixPkgs = [
  'nodejs-20_x',
  'npm-9_x',
  'python3'
]
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
nixpkgsArchive = 'a8a3c3b3e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9'  # Updated to a newer Nixpkgs archive

[phases.install]
cmds = [
  "npm ci --prefer-offline --no-audit",
  "cd TrueNorthAdmin && npm ci --prefer-offline --no-audit",
  "cd server && npm ci --prefer-offline --no-audit"
]

[phases.build]
cmds = [
  "npm run build:main",
  "npm run build:admin", 
  "npm run build:combine"
]

[start]
cmd = "node server.js"
