name: Deploy to Coolify

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install admin dependencies
      run: cd TrueNorthAdmin && npm ci
    
    - name: Lint main project
      run: npm run lint
    
    - name: Lint admin project
      run: cd TrueNorthAdmin && npm run lint
    
    - name: Build project
      run: npm run build
    
    - name: Test build output
      run: |
        ls -la dist/
        ls -la dist/admin-dashboard/ || echo "Admin dashboard not found"
